import initScrollSuave from "./js/modules/scroll-suave.js";
import initAnimacaoScroll from "./js/modules/anima-scroll.js";
import initAccordion from "./js/modules/anima-accord.js";
import initTabNav from "./js/modules/anima-tabNav.js";
import { initModal, closeModal } from "./js/modules/modal.js";
import submitForm from "./js/modules/submit.js";
import initDropdownMenu from "./js/modules/dropdown-menu.js";
import initMenuMobile from "./js/modules/menu-mobile.js";
import animaNumeros from "./js/modules/anima-numeros.js";
import workingTime from "./js/modules/funcionamento.js";

initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
closeModal();
submitForm();
initDropdownMenu();
initMenuMobile();
animaNumeros(); 
workingTime();